### ISSUE TITLE
Header Chat

### ISSUE THREAD

**Issue by NMA93** [logrinto/IAD2017.chat#2]
Als User möchte ich im Chat jederzeit sehen mit wem ich chatte. 

Anforderung Mobile: 

Header 1 im Chat:
Im Chat einen Header platzieren mit Infos zum Chatpartner.
Header ist nur im Chat sichtbar und nicht über den Kontakten.

Header 2 Kontakte:
Möglichkeit einen Header zu platzieren.
Header ist nur in Kontakte sichtbar und nicht im Chat.

**Comment by signalwerk** [comment]
## Header 1 im Chat
finde ich gut! ich implementiere dies.

## Header 2 Kontakte
hmm... ok. was soll da stehen?

**Comment by NMA93** [comment]
> hmm... ok. was soll da stehen?

Ich habe da an Funktionen wie "Neuer Chat" oder "Chats-Durchsuchen" gedacht. Dies könnte aber für unsere Aufgabe auch ein wenig "Out-of-Scope" sein. Ich kann damit leben wenn wir den Header ausserhalb der Chats komplett weglassen.

**Comment by stfffchs** [comment]
Hallo, wir wären für den Chats Header. Dieser hätte den Titel Chats und würde das eigene Profilbild und das Icon für "Neue Nachricht verfassen" enthalten. Die Frage ist: muss alles was angezeigt wird funktionieren?

**Comment by matthiasmeierkoch** [comment]
Live

**Comment by NMA93** [comment]
@signalwerk Hallo Stefan, ich habe gestern dieses Issue kurz reviewt. Mir ist aufgefallen dass der Header zwar im Chat vorhanden ist. Dieser wird aber auch oberhalb der Kontakte/Chat Ansicht benötigt. Ist es möglich dort ebenfalls (die Möglichkeit) für einen Header einzubauen?  Ob dieser dann verwendet wird und in welcher Form kann jeder Gruppe selber überlassen werden. 

![Header](https://user-images.githubusercontent.com/23292494/57600662-bbd02e80-755a-11e9-887b-a0752851cec3.png)

**Comment by signalwerk** [comment]
@NMA93 sorry für die späte antwort. wenn du einfach einen statischen Header drin möchtest, kannst du das mit CSS alleine machen. so etwas wie:

```css
.App__ConversationList {
  position: relative;
}

.App__ConversationList::before {
  display: block;
  content: "Chat";
  position: absolute;
  top: 0;
  left: 0;
  height: 3rem;  /* height of head */
  text-align: center;
  background-color: yellow;
}

.ConversationList {
    margin-top: 3rem; /* push content down */
    height: calc(100% - 3rem); /* height minus head */
}

```

![image](https://user-images.githubusercontent.com/992878/58020129-8e115980-7b07-11e9-8646-b945dab5fd42.png)


reicht dir das? oder brauchst du etwas anderes?
