### ISSUE TITLE
Status online/offline

### ISSUE THREAD

**Issue by stfffchs** [logrinto/IAD2017.chat#6]
Der Status online/offline soll ersichtlich sein. Wir schlagen eine Markierung beim Profilbild vor.

**Comment by signalwerk** [comment]
Guter Hinweis. Man könnte sich auch denken, das man so ein «Last seen: 00:05» hat, wenn man offline ist. 

Ich habe nun eine Schätzung für die Implementierung dieses Issues abgegeben (siehe Tag). Am kommenden Freitag sprechen wir über die offenen Issues und entscheiden gemeinsam, welche Features als nächstes implementiert werden. Ich hoffe das ist ok für dich.

**Comment by signalwerk** [comment]
Es gibt nun eine weitere Klasse. So kann man einen Online-Status anzeigen. `.ConversationItem` hat dann noch eine weitere Klasse `.ConversationItem--online`.

### Beispiel

```css
.ConversationItem {
  /* bestehendes CSS */
  position: relative;
}

.ConversationItem--online::after {
  display: block;
  content: "";
  width: 1rem;
  height: 1rem;
  border-radius: 50%;
  background-color: green;
  top: 1rem;
  left: 1rem;
  position: absolute;
}
```
